services:
  ocre-wasm:
    build:
      context: .
      dockerfile: Dockerfile.sdk
    container_name: ocre-wasm
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true

  ocre-zephyr:
    build:
      context: .
      dockerfile: Dockerfile.zephyr
    container_name: ocre-zephyr
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    user: root

  ocre-linux:
    build:
      context: .
      dockerfile: Dockerfile.linux
    container_name: ocre-linux
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
